---
title: "Rtadjustement_testD"
author: "Philippine Louail"
date: "2023-11-27"
output: html_document
---

# Packages

```{r packages}
library(MsExperiment)
library(RSQLite)
library(xcms)
library(Spectra)
library(RColorBrewer)
library(pander)
library(readxl)
library(MetaboCoreUtils)
library(pheatmap)
library(MsBackendSql)
library(SummarizedExperiment)
```

```{r}
load("nafld_after_refine")
#' Define colors for the groups.
#' Sample type
col_phenotype <- brewer.pal(8, "Accent")[c(1, 3, 5, 4, 8)]
names(col_phenotype) <- c("Study", "Pool_IS_Dil", "Pool", "Pool_Dil", "Blank")

col_sample <- col_phenotype[sampleData(nafld)$sample_type] 

#' Batches 
col_batch_id <- brewer.pal(7, "Paired")[c(4, 3, 1, 5, 2, 6, 7)]
names(col_batch_id) <- c("BATCH0125", "BATCH0130", "BATCH0143",
                        "BATCH0159", "BATCH0165", "BATCH0169",
                        "BATCH0186")

col_batches <- col_batch_id[sampleData(nafld)$batch_id]


#' Set up parallel processing using 2 cores
if (.Platform$OS.type == "unix") {
    register(bpstart(MulticoreParam(2)))
} else {
    register(bpstart(SnowParam(2)))
}
```

```{r}
#'reorganising samples order for alignment
#' saving old order
sampleData(nafld)$original_index <- seq_along(nafld)

#' determining new order
sd <- as.data.frame(sampleData(nafld))
tmp <- lapply(split(sd, sd$batch_id), function(batch){
    qcs <- which(batch$sample_type == "Pool")
    indices <- batch$original_index
    first <- min(qcs)
    last <- max(qcs)
    c(indices[first], indices[-c(first, last)], indices[last])
})

index_qc <- unlist(tmp, use.names = FALSE)

#' applying it
nafld <- nafld[index_qc]
#' triple checked, it worked perfectly
```

```{r}
## first run based on IS - full then try pool only 
#' creating matrice for rt alignment 
intern_standard <- read.delim("Mix_alignment.txt")

library(MetaboAnnotation)

# prep
fdef <- as.data.frame(chromPeaks(nafld))
fdef$feature_id <- rownames(fdef)
final_table <- matrix(
    ncol = 530, 
    nrow = nrow(intern_standard), 
    dimnames = list(c(row.names(intern_standard)), c(1:530))
)

#' Keep only matches with highest intensity 
rem_dups <- function(x) {
    if (nrow(matches(x)) > 1)
        filterMatches(x, index = which.max(x$target_maxo))
    else x
}

for (i in unique(fdef$sample)){
    tmp <- fdef[fdef[,"sample"]== i, ]
    if(sampleData(nafld)$sample_type[i] == "Pool") {
        match_intern_standard <- matchValues(
        query = intern_standard,
        target = tmp,
        mzColname = c("mz", "mz"),
        rtColname = c("RT", "rt" ),
        param = MzRtParam(ppm = 50, toleranceRt = 20))
    match_intern_standard <- MetaboAnnotation::endoapply(match_intern_standard,
                                                     FUN = rem_dups)
    final_table[,i] <- match_intern_standard$target_rt
    } 
}

#' if need to use only the pool
index <- sampleData(nafld)$sample_type == "Pool"
final_table <- final_table[, index] 
#' run with that first
#' Define parameters of choice
subset <- which(sampleData(nafld)$sample_type == "Pool")
param <- PeakGroupsParam(minFraction = 0.9,
                         span = 0.6, 
                         peakGroupsMatrix = final_table,
                         subset = subset, 
                         subsetAdjust = "average")

nafld <- adjustRtime(nafld, param = param, chunkSize = 2L)

#' See result
plotAdjustedRtime(nafld, col = col_sample)
grid()
legend("topright", col = col_phenotype,
       legend = names(col_phenotype), lty = 1)

plotAdjustedRtime(nafld, col = col_batches)
grid()
legend("topright", col = col_batch_id,
       legend = names(col_batch_id), lty = 1)

nafld <- applyAdjustedRtime(nafld)

nafld <- nafld[order(sampleData(nafld)$original_index), keepFeatures = TRUE, keepAdjustedRtime = TRUE]

save(nafld, file= "strategyD")
```


```{r}
pool_index <- sampleData(nafld)$sample_type == "Pool"
pool_sample <- nafld[pool_index]
batches_pool <- col_batch_id[sampleData(pool_sample)$batch_id]

eics <- chromatogram(pool_sample,
                     mz = as.matrix(intern_standard[, c("mzmin", "mzmax")]),
                     rt = as.matrix(intern_standard[, c("rtmin", "rtmax")]))

dr <- "testD/withpeaks"
dir.create(dr, recursive = TRUE, showWarnings = FALSE)

for (i in seq_len(nrow(intern_standard))) {
    png(paste0(dr, "EIC_", intern_standard$abbreviation[i], ".png"),
        width = 12, height = 8, units = "cm", res = 600, pointsize = 4)
    plot(eics[i], main =intern_standard$name[i],
         col = batches_pool,
         peakCol = col_sample[chromPeaks(eics[i])[, "sample"]],
         peakBg = paste0(col_sample[chromPeaks(eics[i])[, "sample"]], 40))
    grid()
    legend("topright", col = col_batch_id,
           legend = names(col_batch_id), lty = 1)
    abline(v = intern_standard$RT[i], col = "red", lty = 3)
    dev.off()
}

```

